//
//  GenericWebViewRouter.swift
//  edenred-iphone
//
//  Created by Josep Bordes Jové on 21/05/2019.
//  Copyright (c) 2019 Inqbarna. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol GenericWebViewRoutingLogic {
    func routeToEndForm()
}

protocol GenericWebViewDataPassing {
    var dataStore: GenericWebViewDataStore? { get }
}

class GenericWebViewRouter: NSObject, GenericWebViewRoutingLogic, GenericWebViewDataPassing {
    weak var viewController: GenericWebViewViewController?
    var dataStore: GenericWebViewDataStore?

    // MARK: Routing

    func routeToEndForm() {
        let destinationVC = EndFormViewController()
        var destinationDS = destinationVC.router!.dataStore!
        passDataToEndForm(source: dataStore!, destination: &destinationDS)
        navigateToEndForm(source: viewController!, destination: destinationVC)
    }

    // MARK: Navigation

    func navigateToEndForm(source: GenericWebViewViewController, destination: EndFormViewController) {
        let navigationController = UINavigationController(rootViewController: destination)
        source.present(navigationController, animated: true, completion: nil)
    }

    // MARK: Passing data

    func passDataToEndForm(source: GenericWebViewDataStore, destination: inout EndFormDataStore) {
        destination.context = source.context
    }
}
