//
//  GenericWebViewInteractor.swift
//  edenred-iphone
//
//  Created by Josep Bordes Jové on 21/05/2019.
//  Copyright (c) 2019 Inqbarna. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol GenericWebViewBusinessLogic {
    func prepareWebView(request: GenericWebView.PrepareWebView.Request)
}

protocol GenericWebViewDataStore: DependencyInjectable {
    var userDefinedUrlsString: [String] { get set }
    var webViewURL: String? { get set }
    var successUrls: [String] { get }
}

class GenericWebViewInteractor: GenericWebViewBusinessLogic, GenericWebViewDataStore {
    var presenter: GenericWebViewPresentationLogic?

    // MARK: Data store

    var userDefinedUrlsString: [String] = []
    var webViewURL: String?
    var context: [Dependency: Any?]?

    var successUrls: [String] {
        userDefinedUrlsString
    }

    // MARK: Business logic

    func prepareWebView(request: GenericWebView.PrepareWebView.Request) {
        let response = GenericWebView.PrepareWebView.Response(urlString: webViewURL)
        presenter?.presentWebView(response: response)
    }
}
