//
//  GenericWebViewRouter.swift
//  edenred-iphone
//
//  Created by Josep Bordes Jové on 21/05/2019.
//  Copyright (c) 2019 Inqbarna. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol GenericWebViewRoutingLogic {
    // func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol GenericWebViewDataPassing {
    var dataStore: GenericWebViewDataStore? { get }
}

class GenericWebViewRouter: NSObject, GenericWebViewRoutingLogic, GenericWebViewDataPassing {
    weak var viewController: GenericWebViewViewController?
    var dataStore: GenericWebViewDataStore?

    // MARK: Routing

    // func routeToSomewhere(segue: UIStoryboardSegue?) {
    //  if let segue = segue {
    //    let destinationVC = segue.destination as! SomewhereViewController
    //    var destinationDS = destinationVC.router!.dataStore!
    //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
    //  } else {
    //    let storyboard = UIStoryboard(name: "Main", bundle: nil)
    //    let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
    //    var destinationDS = destinationVC.router!.dataStore!
    //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
    //    navigateToSomewhere(source: viewController!, destination: destinationVC)
    //  }
    // }

    // MARK: Navigation

    // func navigateToSomewhere(source: GenericWebViewViewController, destination: SomewhereViewController) {
    //  source.show(destination, sender: nil)
    // }

    // MARK: Passing data

    // func passDataToSomewhere(source: GenericWebViewDataStore, destination: inout SomewhereDataStore) {
    //  destination.name = source.name
    // }
}
