//
//  EndFormInteractor.swift
//  coronasurveys-ios
//
//  Created by Josep Bordes Jové on 18/05/2020.
//  Copyright (c) 2020 Inqbarna. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol EndFormBusinessLogic {
    func prepareView(request: EndForm.PrepareView.Request)
    func scheduleNotification(request: EndForm.ScheduleNotification.Request)
}

protocol EndFormDataStore: DependencyInjectable {
    // var name: String { get set }
}

class EndFormInteractor: EndFormBusinessLogic, EndFormDataStore {
    var presenter: EndFormPresentationLogic?

    // MARK: Data store

    var context: [Dependency: Any?]?

    // MARK: Workers

    let workers = PreferencesWorker(store: PreferencesStore())

    // MARK: Busniess logic

    func prepareView(request: EndForm.PrepareView.Request) {
        let response = EndForm.PrepareView.Response()
        presenter?.presentView(response: response)
    }

    func scheduleNotification(request: EndForm.ScheduleNotification.Request) {
        workers.scheduleNotification(for: request.interval)
        let response = EndForm.ScheduleNotification.Response()
        presenter?.presentScheduleNotification(response: response)
    }
}
