//
//  EndFormPresenter.swift
//  coronasurveys-ios
//
//  Created by Josep Bordes Jové on 18/05/2020.
//  Copyright (c) 2020 Inqbarna. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol EndFormPresentationLogic {
    func presentView(response: EndForm.PrepareView.Response)
}

class EndFormPresenter: EndFormPresentationLogic {
    weak var viewController: EndFormDisplayLogic?

    func presentView(response: EndForm.PrepareView.Response) {
        let viewModel = EndForm.PrepareView.ViewModel()
        viewController?.displayView(viewModel: viewModel)
    }
}
