line_length: 160
cyclomatic_complexity: 20
function_body_length: 60

identifier_name:
  allowed_symbols: "_"
  min_length: 3
  max_length:
    warning: 70
    error: 160
  excluded:
    - id
    - vm
    - vc
    - to
    - in

nesting:
  type_level: 3

type_name:
  min_length: 3
  max_length:
    warning: 70
    error: 160
  excluded:
    - Id
    - in

disabled_rules:
  - multiple_closures_with_trailing_closure

excluded:
  - coronasurveys-ios/L10N.swift
  - Pods
  - .bundle
