//
// L10N.swift
//
// Copyright (c) 2020 InQBarna Kenkyuu Jo (http://inqbarna.com/)
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.
//

import Foundation

// DO NOT EDIT. This file is autogenerated by Fluent Localization.

func TR(_ key: String, _ text: String, comment: String) -> String {
    __TR(key, text, comment: comment)
}

func TR(_ key: String, _ text: String) -> String {
    __TR(key, text, comment: nil)
}

func TR(_ key: String, comment: String) -> String {
    __TR(key, nil, comment: comment)
}

func TR(_ key: String) -> String {
    __TR(key, nil, comment: nil)
}

func TRP(_ key: String, _ text: String, comment: String) -> String {
    __TR(key, text, comment: comment)
}

func TRP(_ key: String, _ text: String) -> String {
    __TR(key, text, comment: nil)
}

func TRP(_ key: String, comment: String) -> String {
    __TR(key, nil, comment: comment)
}

func TRP(_ key: String) -> String {
    __TR(key, nil, comment: nil)
}

private func __TR(_ key: String, _ text: String?, comment: String?) -> String {
    guard let text = text else {
        return NSLocalizedString(key, comment: comment ?? "")
    }
    return NSLocalizedString(text, comment: comment ?? "")
}

struct L10N {}

extension L10N {
    /**
      Date: Wed Apr 7 10:55:55 2021

      *Default value (en)*

      *“The world is suffering from a pandemic called COVID-19, caused by the SARS-CoV-2 virus. When testing availability and other resources are limited, national and local governments can encounter problems evaluating the reach and evolution of the epidemic. Hence, any means to evaluate the evolution of the pandemic and its impact with reasonable level of accuracy is useful.\nThe objective of this study is the collection and publication of data concerning the COVID-19 pandemic in different countries. This data is useful to estimate multiple parameters of the pandemic and their evolution in a simple, cheap, and homogeneous way across countries, in combination with other data sources. These numbers are, for instance, the number of infected persons with the COVID-19 virus, the number of fatalities, the number of people vaccinated, etc. They are estimated at a given point in time in each country, and their evolution over time, using techniques like the Network Scale-up Method.”*
     */
    static var aboutProjectText: String {
        NSLocalizedString("about_project_text", comment: "Date: Wed Apr 7 10:55:55 2021")
    }

    /**
      No comment provided

      *Default value (en)*

      *“About the project”*
     */
    static var aboutProjectTitle: String {
        NSLocalizedString("about_project_title", comment: "")
    }

    /**
      No comment provided

      *Default value (en)*

      *“Add a reminder so it is easier for you to fill in the survey regularly and make a better contribution to the project.”*
     */
    static var addReminderText: String {
        NSLocalizedString("add_reminder_text", comment: "")
    }

    /**
      No comment provided

      *Default value (en)*

      *“Add reminder”*
     */
    static var addReminderTitle: String {
        NSLocalizedString("add_reminder_title", comment: "")
    }

    /**
      No comment provided

      *Default value (en)*

      *“All collected data”*
     */
    static var allCollectedData: String {
        NSLocalizedString("all_collected_data", comment: "")
    }

    /**
      No comment provided

      *Default value (en)*

      *“Cancel”*
     */
    static var cancel: String {
        NSLocalizedString("cancel", comment: "")
    }

    /**
      No comment provided

      *Default value (en)*

      *“CoronaSurveys”*
     */
    static var coronasurveys: String {
        NSLocalizedString("coronasurveys", comment: "")
    }

    /**
      No comment provided

      *Default value (en)*

      *“Daily reminder”*
     */
    static var dailyReminder: String {
        NSLocalizedString("daily_reminder", comment: "")
    }

    /**
      No comment provided

      *Default value (en)*

      *“Email”*
     */
    static var emailUs: String {
        NSLocalizedString("email_us", comment: "")
    }

    /**
      No comment provided

      *Default value (en)*

      *“Enable notifications to schedule reminders”*
     */
    static var enableNotificationsAlertText: String {
        NSLocalizedString("enable_notifications_alert_text", comment: "")
    }

    /**
      No comment provided

      *Default value (en)*

      *“Notifications not enabled”*
     */
    static var enableNotificationsAlertTitle: String {
        NSLocalizedString("enable_notifications_alert_title", comment: "")
    }

    /**
      No comment provided

      *Default value (en)*

      *“Fill the survey”*
     */
    static var fillSurvey: String {
        NSLocalizedString("fill_survey", comment: "")
    }

    /**
      No comment provided

      *Default value (en)*

      *“You can also follow us on social networks and share our work:”*
     */
    static var followUsText: String {
        NSLocalizedString("follow_us_text", comment: "")
    }

    /**
      No comment provided

      *Default value (en)*

      *“Follow us!”*
     */
    static var followUsTitle: String {
        NSLocalizedString("follow_us_title", comment: "")
    }

    /**
      No comment provided

      *Default value (en)*

      *“Gmail”*
     */
    static var gmailApp: String {
        NSLocalizedString("gmail_app", comment: "")
    }

    /**
      No comment provided

      *Default value (en)*

      *“Go to settings”*
     */
    static var goToSettings: String {
        NSLocalizedString("go_to_settings", comment: "")
    }

    /**
      No comment provided

      *Default value (en)*

      *“Please complete our short surveys! Choose a country in which you have contacts, and answer questions about how  the pandemic is affecting those you know. No personal information is collected nor stored in these surveys. Because each of us can provide information about the situation among our direct contacts, in aggregate we are able to get rough estimates of total cases, new cases, fatalities, vaccination levels, etc.\nBecause we are tracking the evolution of this epidemic over time, once you have completed the survey, please remember to come back and update the survey at least once a week, or when the responses change.\nFinally, you can help us by asking your friends, colleagues and relatives to complete the survey as well! Thank you!”*
     */
    static var howHelpBody: String {
        NSLocalizedString("how_help_body", comment: "")
    }

    /**
      No comment provided

      *Default value (en)*

      *“How can I help?”*
     */
    static var howHelpTitle: String {
        NSLocalizedString("how_help_title", comment: "")
    }

    /**
      No comment provided

      *Default value (en)*

      *“Using the number of survey responses you and other participants provide, our methods are able to estimate the incidence and evolution of the pandemic.”*
     */
    static var howItWorksBody: String {
        NSLocalizedString("how_it_works_body", comment: "")
    }

    /**
      No comment provided

      *Default value (en)*

      *“How does it work?”*
     */
    static var howItWorksTitle: String {
        NSLocalizedString("how_it_works_title", comment: "")
    }

    /**
      No comment provided

      *Default value (en)*

      *“Mail”*
     */
    static var mailApp: String {
        NSLocalizedString("mail_app", comment: "")
    }

    /**
      No comment provided

      *Default value (en)*

      *“No mail apps available”*
     */
    static var noMailAppsAvailable: String {
        NSLocalizedString("no_mail_apps_available", comment: "")
    }

    /**
      No comment provided

      *Default value (en)*

      *“No, thanks”*
     */
    static var noThanks: String {
        NSLocalizedString("no_thanks", comment: "")
    }

    /**
      No comment provided

      *Default value (en)*

      *“Outlook”*
     */
    static var outlookApp: String {
        NSLocalizedString("outlook_app", comment: "")
    }

    /**
      No comment provided

      *Default value (en)*

      *“Estimates of active cases”*
     */
    static var percentagePopulationSymptoms: String {
        NSLocalizedString("percentage_population_symptoms", comment: "")
    }

    /**
      No comment provided

      *Default value (en)*

      *“The CoronaSurveys project is a collaborative endeavour between several universities, research institutions and independent volunteers. Data about the COVID-19 pandemic has been collected since March 2020 via anonymous open surveys (all the data collected is openly available). This data allows the production of estimates on the incidence and evolution of COVID-19 using the Network Scale-up Method.\n”*
     */
    static var projectSummaryText: String {
        NSLocalizedString("project_summary_text", comment: "")
    }

    /**
      No comment provided

      *Default value (en)*

      *“The CoronaSurveys Project”*
     */
    static var projectSummaryTitle: String {
        NSLocalizedString("project_summary_title", comment: "")
    }

    /**
      No comment provided

      *Default value (en)*

      *“Reminder disabled”*
     */
    static var reminderDisabled: String {
        NSLocalizedString("reminder_disabled", comment: "")
    }

    /**
      No comment provided

      *Default value (en)*

      *“Reminder enabled”*
     */
    static var reminderEnabled: String {
        NSLocalizedString("reminder_enabled", comment: "")
    }

    /**
      No comment provided

      *Default value (en)*

      *“Fill the anonymous survey for a country”*
     */
    static var reminderNotificationBody: String {
        NSLocalizedString("reminder_notification_body", comment: "")
    }

    /**
      No comment provided

      *Default value (en)*

      *“Contribute”*
     */
    static var reminderNotificationTitle: String {
        NSLocalizedString("reminder_notification_title", comment: "")
    }

    /**
      No comment provided

      *Default value (en)*

      *“Select country”*
     */
    static var selectCountry: String {
        NSLocalizedString("select_country", comment: "")
    }

    /**
      No comment provided

      *Default value (en)*

      *“Select mail app”*
     */
    static var selectMailApp: String {
        NSLocalizedString("select_mail_app", comment: "")
    }

    /**
      No comment provided

      *Default value (en)*

      *“Contribute and fill the anonymous survey for a country:”*
     */
    static var selectYourCountryAndStart: String {
        NSLocalizedString("select_your_country_and_start", comment: "")
    }

    /**
      No comment provided

      *Default value (en)*

      *“I would like to have more information about the project”*
     */
    static var sendMailSubject: String {
        NSLocalizedString("send_mail_subject", comment: "")
    }

    /**
      No comment provided

      *Default value (en)*

      *“Settings”*
     */
    static var settings: String {
        NSLocalizedString("settings", comment: "")
    }

    /**
      No comment provided

      *Default value (en)*

      *“Survey”*
     */
    static var survey: String {
        NSLocalizedString("survey", comment: "")
    }

    /**
      No comment provided

      *Default value (en)*

      *“Team”*
     */
    static var team: String {
        NSLocalizedString("team", comment: "")
    }

    /**
      No comment provided

      *Default value (en)*

      *“Weekly reminder”*
     */
    static var weeklyReminder: String {
        NSLocalizedString("weekly_reminder", comment: "")
    }

    /**
      No comment provided

      *Default value (en)*

      *“This is an indirect and very cost-effective method that can act as a supplementary tool for health care providers and governments planning and implementing pandemic response.”*
     */
    static var whyImportantBody: String {
        NSLocalizedString("why_important_body", comment: "")
    }

    /**
      No comment provided

      *Default value (en)*

      *“Why is it important to participate?”*
     */
    static var whyImportantTitle: String {
        NSLocalizedString("why_important_title", comment: "")
    }
}
