//
// L10N.swift
//
// Copyright (c) 2020 InQBarna Kenkyuu Jo (http://inqbarna.com/)
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.
//

import Foundation

// DO NOT EDIT. This file is autogenerated by Fluent Localization.

func TR(_ key: String, _ text: String, comment: String) -> String {
    __TR(key, text, comment: comment)
}

func TR(_ key: String, _ text: String) -> String {
    __TR(key, text, comment: nil)
}

func TR(_ key: String) -> String {
    __TR(key, nil, comment: nil)
}

func TRP(_ key: String, _ text: String, comment: String) -> String {
    __TR(key, text, comment: comment)
}

func TRP(_ key: String, _ text: String) -> String {
    __TR(key, text, comment: nil)
}

func TRP(_ key: String) -> String {
    __TR(key, nil, comment: nil)
}

private func __TR(_ key: String, _ text: String?, comment: String?) -> String {
    guard let text = text else {
        return NSLocalizedString(key, comment: comment ?? "")
    }
    return NSLocalizedString(text, comment: comment ?? "")
}

struct L10N {}

extension L10N {
    /**
      No comment provided

      *Default value (en)*

      *“The world is suffering from a pandemic called COVID-19, caused by the SARS-CoV-2 virus. The different national governments have problems evaluating the reach of the epidemic, having limited resources and tests to their disposal. Hence, any means to evaluate the number of persons with symptoms compatible with COVID-19 with reasonable level of accuracy is useful.\n\nThe objective of this study is the collection and publication of data concerning the number of people that show symptoms compatible with COVID-19 in different countries. Hopefully, this data will be useful to estimate the number of infected persons with the COVID-19 virus at a given point in time in these countries, and the evolution of this number over time.”*
     */
    static var aboutProjectText: String {
        NSLocalizedString("about_project_text", comment: "")
    }

    /**
      No comment provided

      *Default value (en)*

      *“About the project”*
     */
    static var aboutProjectTitle: String {
        NSLocalizedString("about_project_title", comment: "")
    }

    /**
      No comment provided

      *Default value (en)*

      *“Add a reminder so it is easier for you to fill in the survey regularly and make a better contribution to the project.”*
     */
    static var addReminderText: String {
        NSLocalizedString("add_reminder_text", comment: "")
    }

    /**
      No comment provided

      *Default value (en)*

      *“Add reminder”*
     */
    static var addReminderTitle: String {
        NSLocalizedString("add_reminder_title", comment: "")
    }

    /**
      No comment provided

      *Default value (en)*

      *“All collected data”*
     */
    static var allCollectedData: String {
        NSLocalizedString("all_collected_data", comment: "")
    }

    /**
      No comment provided

      *Default value (en)*

      *“Cancel”*
     */
    static var cancel: String {
        NSLocalizedString("cancel", comment: "")
    }

    /**
      No comment provided

      *Default value (en)*

      *“CoronaSurveys”*
     */
    static var coronasurveys: String {
        NSLocalizedString("coronasurveys", comment: "")
    }

    /**
      No comment provided

      *Default value (en)*

      *“Daily reminder”*
     */
    static var dailyReminder: String {
        NSLocalizedString("daily_reminder", comment: "")
    }

    /**
      No comment provided

      *Default value (en)*

      *“Email”*
     */
    static var emailUs: String {
        NSLocalizedString("email_us", comment: "")
    }

    /**
      No comment provided

      *Default value (en)*

      *“Fill the survey”*
     */
    static var fillSurvey: String {
        NSLocalizedString("fill_survey", comment: "")
    }

    /**
      No comment provided

      *Default value (en)*

      *“You can also follow us on social networks and share our work:”*
     */
    static var followUsText: String {
        NSLocalizedString("follow_us_text", comment: "")
    }

    /**
      No comment provided

      *Default value (en)*

      *“Follow us!”*
     */
    static var followUsTitle: String {
        NSLocalizedString("follow_us_title", comment: "")
    }

    /**
      No comment provided

      *Default value (en)*

      *“Gmail”*
     */
    static var gmailApp: String {
        NSLocalizedString("gmail_app", comment: "")
    }

    /**
      No comment provided

      *Default value (en)*

      *“Mail”*
     */
    static var mailApp: String {
        NSLocalizedString("mail_app", comment: "")
    }

    /**
      No comment provided

      *Default value (en)*

      *“No mail apps available”*
     */
    static var noMailAppsAvailable: String {
        NSLocalizedString("no_mail_apps_available", comment: "")
    }

    /**
      No comment provided

      *Default value (en)*

      *“No, thanks”*
     */
    static var noThanks: String {
        NSLocalizedString("no_thanks", comment: "")
    }

    /**
      No comment provided

      *Default value (en)*

      *“Outlook”*
     */
    static var outlookApp: String {
        NSLocalizedString("outlook_app", comment: "")
    }

    /**
      No comment provided

      *Default value (en)*

      *“Percentage of population with symptoms estimated by @CoronaSurveys”*
     */
    static var percentagePopulationSymptoms: String {
        NSLocalizedString("percentage_population_symptoms", comment: "")
    }

    /**
      No comment provided

      *Default value (en)*

      *“The CoronaSurveys project is a collaborative endeavour from several universities and research institutions (team members) Data about COVID-19 cases is collected via anonymous open surveys (all the data collected is openly available). The results below present estimations on the incidence of COVID-19 from this and other available data. You can help by regularly completing the anonymous survey.\n”*
     */
    static var projectSummaryText: String {
        NSLocalizedString("project_summary_text", comment: "")
    }

    /**
      No comment provided

      *Default value (en)*

      *“CoronaSurveys Project Summary”*
     */
    static var projectSummaryTitle: String {
        NSLocalizedString("project_summary_title", comment: "")
    }

    /**
      No comment provided

      *Default value (en)*

      *“Reminder enabled”*
     */
    static var reminderEnabled: String {
        NSLocalizedString("reminder_enabled", comment: "")
    }

    /**
      No comment provided

      *Default value (en)*

      *“Fill the anonymous survey for a country”*
     */
    static var reminderNotificationBody: String {
        NSLocalizedString("reminder_notification_body", comment: "")
    }

    /**
      No comment provided

      *Default value (en)*

      *“Contribute”*
     */
    static var reminderNotificationTitle: String {
        NSLocalizedString("reminder_notification_title", comment: "")
    }

    /**
      No comment provided

      *Default value (en)*

      *“Select country”*
     */
    static var selectCountry: String {
        NSLocalizedString("select_country", comment: "")
    }

    /**
      No comment provided

      *Default value (en)*

      *“Select mail app”*
     */
    static var selectMailApp: String {
        NSLocalizedString("select_mail_app", comment: "")
    }

    /**
      No comment provided

      *Default value (en)*

      *“Contribute and fill the anonymous survey for a country:”*
     */
    static var selectYourCountryAndStart: String {
        NSLocalizedString("select_your_country_and_start", comment: "")
    }

    /**
      No comment provided

      *Default value (en)*

      *“I would like to have more information about the project”*
     */
    static var sendMailSubject: String {
        NSLocalizedString("send_mail_subject", comment: "")
    }

    /**
      No comment provided

      *Default value (en)*

      *“Settings”*
     */
    static var settings: String {
        NSLocalizedString("settings", comment: "")
    }

    /**
      No comment provided

      *Default value (en)*

      *“Survey”*
     */
    static var survey: String {
        NSLocalizedString("survey", comment: "")
    }

    /**
      No comment provided

      *Default value (en)*

      *“Team”*
     */
    static var team: String {
        NSLocalizedString("team", comment: "")
    }

    /**
      No comment provided

      *Default value (en)*

      *“Weekly reminder”*
     */
    static var weeklyReminder: String {
        NSLocalizedString("weekly_reminder", comment: "")
    }
}
