//
//  SplashScreenPresenter.swift
//  coronasurveys-ios
//
//  Created by Josep Bordes Jové on 18/05/2020.
//  Copyright (c) 2020 Inqbarna. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SplashScreenPresentationLogic {
    func presentView(response: SplashScreen.PrepareView.Response)
}

class SplashScreenPresenter: SplashScreenPresentationLogic {
    weak var viewController: SplashScreenDisplayLogic?

    // MARK: Do something

    func presentView(response: SplashScreen.PrepareView.Response) {
        let viewModel = SplashScreen.PrepareView.ViewModel()
        viewController?.displayView(viewModel: viewModel)
    }
}
