//
//  HomeRouter.swift
//  coronasurveys-ios
//
//  Created by Josep Bordes Jové on 18/05/2020.
//  Copyright (c) 2020 Inqbarna. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol HomeRoutingLogic {
    func routeToSettings()
    func routeToForm()
}

protocol HomeDataPassing {
    var dataStore: HomeDataStore? { get }
}

class HomeRouter: NSObject, HomeRoutingLogic, HomeDataPassing {
    weak var viewController: HomeViewController?
    var dataStore: HomeDataStore?

    // MARK: Routing

    func routeToSettings() {
        let destinationVC = SettingsViewController()
        var destinationDS = destinationVC.router!.dataStore!
        passDataToSettings(source: dataStore!, destination: &destinationDS)
        navigateToSettings(source: viewController!, destination: destinationVC)
    }

    func routeToForm() {
        let destinationVC = GenericWebViewViewController()
        var destinationDS = destinationVC.router!.dataStore!
        passDataToForm(source: dataStore!, destination: &destinationDS)
        navigateToForm(source: viewController!, destination: destinationVC)
    }

    // MARK: Navigation

    func navigateToSettings(source: HomeViewController, destination: SettingsViewController) {
        let navigationController = UINavigationController(rootViewController: destination)
        source.present(navigationController, animated: true, completion: nil)
    }

    func navigateToForm(source: HomeViewController, destination: GenericWebViewViewController) {
        let navigationController = UINavigationController(rootViewController: destination)
        navigationController.modalPresentationStyle = .overFullScreen
        source.present(navigationController, animated: true, completion: nil)
    }

    // MARK: Passing data

    func passDataToSettings(source: HomeDataStore, destination: inout SettingsDataStore) {
        destination.context = source.context
    }

    func passDataToForm(source: HomeDataStore, destination: inout GenericWebViewDataStore) {
        destination.context = source.context

        if let countryCode = source.countryCode,
           let languageCode = source.languageCode
        {
            destination.webViewURL = Configuration.surveyUrl(countryCode: countryCode, languageCode: languageCode)
        }
    }
}
