//
//  HomePresenter.swift
//  coronasurveys-ios
//
//  Created by Josep Bordes Jové on 18/05/2020.
//  Copyright (c) 2020 Inqbarna. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomePresentationLogic {
    func presentView(response: Home.PrepareView.Response)
    func presentCountryCode(response: Home.UpdateCountryCode.Response)
}

class HomePresenter: HomePresentationLogic {
    weak var viewController: HomeDisplayLogic?

    func presentView(response: Home.PrepareView.Response) {
        let viewModel = Home.PrepareView.ViewModel(
            title: L10N.coronasurveys,
            countryCode: response.countryCode,
            sections: sectionsForCountryCode(response.countryCode)
        )
        viewController?.displayView(viewModel: viewModel)
    }

    func presentCountryCode(response: Home.UpdateCountryCode.Response) {
        let viewModel = Home.UpdateCountryCode.ViewModel(countryCode: response.countryCode)
        viewController?.displayCountryCode(viewModel: viewModel)
    }

    func sectionsForCountryCode(_ countryCode: String) -> [HomeContent] {
        let imageUrl = Configuration.imageUrl.replacingOccurrences(of: "XX", with: countryCode)

        return [
            .summary(text: L10N.projectSummaryText),
            .image(title: L10N.percentagePopulationSymptoms, url: imageUrl),
            .titleBody(title: L10N.howItWorksTitle, body: L10N.howItWorksBody),
            .titleBody(title: L10N.whyImportantTitle, body: L10N.whyImportantBody),
            .titleBody(title: L10N.howHelpTitle, body: L10N.howHelpBody),
            .about(L10N.aboutProjectText),
            .followUs(institutions: [.facebook, .instagram, .twitter]),
            .contactUs
        ]
    }
}
