//
//  HomeInteractor.swift
//  coronasurveys-ios
//
//  Created by Josep Bordes Jové on 18/05/2020.
//  Copyright (c) 2020 Inqbarna. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomeBusinessLogic {
    func prepareView(request: Home.PrepareView.Request)
    func updateCountryCode(request: Home.UpdateCountryCode.Request)
}

protocol HomeDataStore: DependencyInjectable {
    var countryCode: String? { get set }
}

class HomeInteractor: HomeBusinessLogic, HomeDataStore {
    var presenter: HomePresentationLogic?

    // MARK: Data store

    var context: [Dependency: Any?]?
    var countryCode: String? = NSLocale.current.regionCode

    // MARK: Business logic

    func prepareView(request: Home.PrepareView.Request) {
        let response = Home.PrepareView.Response(countryCode: countryCode?.capitalized)
        presenter?.presentView(response: response)
    }

    func updateCountryCode(request: Home.UpdateCountryCode.Request) {
        countryCode = request.newCountryCode
    }
}
