//
//  HomeInteractor.swift
//  coronasurveys-ios
//
//  Created by Josep Bordes Jové on 18/05/2020.
//  Copyright (c) 2020 Inqbarna. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomeBusinessLogic {
    func prepareView(request: Home.PrepareView.Request)
    func updateCountryCode(request: Home.UpdateCountryCode.Request)
}

protocol HomeDataStore: DependencyInjectable {
    var countryCode: String { get }
    var languageCode: String? { get }
}

class HomeInteractor: HomeBusinessLogic, HomeDataStore {
    var presenter: HomePresentationLogic?

    // MARK: Data store

    var context: [Dependency: Any?]?

    var countryCode: String {
        preferencesWorker.retrieveSelectedCountry() ?? NSLocale.current.regionCode ?? "US"
    }

    var languageCode: String? {
        preferencesWorker.retrieveSelectedLanguage() ?? NSLocale.current.languageCode
    }

    // MARK: Worker

    var preferencesWorker = PreferencesWorker(store: PreferencesStore())

    // MARK: Business logic

    func prepareView(request: Home.PrepareView.Request) {
        let response = Home.PrepareView.Response(countryCode: countryCode.uppercased())
        presenter?.presentView(response: response)
    }

    func updateCountryCode(request: Home.UpdateCountryCode.Request) {
        if let newCountryCode = request.newCountryCode {
            preferencesWorker.saveSelectedCountry(newCountryCode)

            let response = Home.UpdateCountryCode.Response(countryCode: newCountryCode)
            presenter?.presentCountryCode(response: response)
        }
    }
}
