//
//  SettingsInteractor.swift
//  coronasurveys-ios
//
//  Created by Josep Bordes Jové on 18/05/2020.
//  Copyright (c) 2020 Inqbarna. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SettingsBusinessLogic {
    func prepareView(request: Settings.PrepareView.Request)
}

protocol SettingsDataStore: DependencyInjectable {
    // var name: String { get set }
}

class SettingsInteractor: SettingsBusinessLogic, SettingsDataStore {
    var presenter: SettingsPresentationLogic?

    // MARK: Data store

    var context: [Dependency: Any?]?

    // MARK: Business logic

    func prepareView(request: Settings.PrepareView.Request) {
        let response = Settings.PrepareView.Response()
        presenter?.presentView(response: response)
    }
}
