//
//  SettingsPresenter.swift
//  coronasurveys-ios
//
//  Created by Josep Bordes Jové on 18/05/2020.
//  Copyright (c) 2020 Inqbarna. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SettingsPresentationLogic {
    func presentView(response: Settings.PrepareView.Response)
    func presentToggleNotification(response: Settings.ToggleNotification.Response)
}

class SettingsPresenter: SettingsPresentationLogic {
    weak var viewController: SettingsDisplayLogic?

    // MARK: Do something

    func presentView(response: Settings.PrepareView.Response) {
        let viewModel = Settings.PrepareView.ViewModel(
            title: NSLocalizedString("settings", comment: ""),
            sections: [.reminders(active: response.hasScheduledNotification)]
        )
        viewController?.displayView(viewModel: viewModel)
    }

    func presentToggleNotification(response: Settings.ToggleNotification.Response) {
        let viewModel = Settings.ToggleNotification.ViewModel(sections: [.reminders(active: response.hasScheduledNotification)])
        viewController?.displayToggleNotification(viewModel: viewModel)
    }
}
