# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

import_from_git(url: 'http://gitlab.inqbarna.com/contrib/xcode-scripts.git', path: 'fastlane/CommonFastfile')
default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
  end

  desc "Submit a new Beta Build to Firebase"
  desc "This will also make sure the profile is up to date"
  lane :firebase do
  	install_profiles
    
    gym(export_method: 'ad-hoc',
        configuration: "Release"
        ) # Build your app - more options available

    firebase_app_distribution(
        app: "1:581222108817:ios:97857d8d890bfc6fc1f930",
        testers: "josep.bordes@inqbarna.com, nacho.sanchez@inqbarna.com"
    )
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    # match(type: "appstore")
    # snapshot
    gym(
      configuration: "AppStore",
      clean: true,
      export_method: "app-store") # Build your app - more options available
    deliver(force: true)
    # frameit
  end
end
